# Site settings
title: Service Ventures
email: info@vcfirm.com
description: >-
  A Credit Union Venture Capital Firm.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brian-sv-prod.github.io/sv-website" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num/"

# Collections
collections:
  portfolio:
    output: true

# Blog permalink
permalink: /sv-website/blog/:title/

# Default front matter
defaults:
  - scope:
      path: "/blog"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/portfoilio"
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: ""
    values:
      layout: "default"

# Include specific files/folders
include:
  - _pages
  
# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - package.json
  - package-lock.json

